language: objective-c
env:
  - RVM_RUBY_VERSION=system
before_install:
  - source ~/.rvm/scripts/rvm && rvm use $RVM_RUBY_VERSION
  - brew install cmake
before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install: bundle install
script: bundle exec rake
branches:
  except:
    - /-job-\d+$/
notifications:
  webhooks:
    urls:
      - http://cocoapods-trunk-service.herokuapp.com/travis/builds
      - http://requestb.in/19f67qf1
    on_success: always
    on_failure: always
    on_start: true
